# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jacob Motley
title: CyberCorps Scholar at University of Tennessee in Chattanooga
email: yqs872@mocs.utc.edu
website: j-h-m.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  j-h-m
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jacob-motley
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Graduate student studying Cyber Secruity at UTC as a member of the CyberCorps program.
  The projects related to Botany were in relation to cross-field collaborative research and tool building between Computer Science and Biology. I worked on these as an Undergraduate.
  My current research interests are Cyber Security, Data Science, ML, and AI. I also enjoy building my own systems and learning about hardware.
  It's safe to say I have a tech addiction at this point.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: collNotes
        link: github.com/j-h-m/collNotes
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/j-h-m/collNotes
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A mobile app for Android and iOS built using Xamarin Forms. It is a modern field-notebook for Biologists, Botanists in particular, to keep up with their specimen collections.
      - layout: left
        title: collBook
        link: github.com/CapPow/collBook
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/j-h-m/collNotes
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A desktop app for Windows, Linux, and Mac, written using Python Qt. The desktop counterpart to collNotes, is what Botanists use in the lab when processing field notes.
      - layout: left
        title: HerbASAP
        link: github.com/CapPow/HerbASAP
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/j-h-m/collNotes
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A desktop app for Windows, Linux, and Mac, written using Python Qt. It incorporates DNN vision algorithms to detect and correct issues in specimen images. I helped write a multithreading library for this app to run models/tasks simultaneously.
  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology some of my other interests are:
      - Mountain Biking
      - Motorcycle Riding
      - Car Racing
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
